# Generated by Django 6.0.5 on 2026-06-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sub',
            new_name='subscribers',
        ),
    ]
